name: Compliance
on: [pull_request]

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    environment: PRD
    env:
      TF_VAR_fws_hostname: ${{ secrets.FWS_HOSTNAME }}
      TF_VAR_fake_token: ${{ secrets.FAKE_TOKEN }}
      TF_VAR_server_count: ${{ secrets.SERVER_COUNT }}

    steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true
      working-directory: ./terraform

    - name: Terraform Init
      id: init
      run: terraform init
      working-directory: ./terraform

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      working-directory: ./terraform

    - name: Terraform Plan
      id: plan
      run: terraform plan -out=tfplan.plan
      working-directory: ./terraform

    - name: Terraform Show
      id: show
      run: terraform show -json tfplan.plan > plan.json
      continue-on-error: true
      working-directory: ./terraform

    - uses: actions/upload-artifact@v4
      with:
        name: plan_json
        path: ./terraform/plan.json

  sentinel:
    name: Sentinel
    needs: terraform
    runs-on: ubuntu-latest
    environment: PRD
    env:
      VERSION: '0.24.1'

    steps:
      - name: Checkout Sentinel Policies
        uses: actions/checkout@v4
        with:
          repository: terraworx/policy-as-code-with-terraform
          path: compliance

      - uses: actions/download-artifact@v4
        with:
          name: plan_json
          path: ./terraform

      - name: Setup Sentinel
        run: |
          mkdir /tmp/sentinel
          curl -o /tmp/sentinel/sentinel.zip https://releases.hashicorp.com/sentinel/${VERSION}/sentinel_${VERSION}_linux_amd64.zip
          unzip -d /tmp/sentinel /tmp/sentinel/sentinel.zip
          echo "/tmp/sentinel" >> $GITHUB_PATH

      - name: Policy Evaluation
        run: sentinel apply -trace -json > sentinel.json
        continue-on-error: true
        working-directory: ./compliance/policy_sets/fakewebservices

      - uses: actions/upload-artifact@v4
        with:
          name: sentinel_json
          path: ./compliance/policy_sets/fakewebservices/sentinel.json